
#include "BANLANCE_EventV1.h"
	 BANLANCE_EventV1::BANLANCE_EventV1(){
		char *actionList[]={
		"eq",
		"VOLUME",
		"DEFAULT",
		"LEFT",
		"RIGHT",
		"UP",
		"DOWN",
		"LIST",
		"MAIN",
		"SRC",
		"CMD",
		"SYS_H",
		"USER_H",
		NULL};
		setActions(actionList);
		initScreen();	
	};
	void BANLANCE_EventV1:: dispatch(MSG_ZHW&msg){
		if(msg.actionName=="eq"&&msg.actionType==NULL_RELEASE){
			_F_eq(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="VOLUME"&&msg.actionType==NULL_RELEASE){
			_F_VOLUME(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="DEFAULT"&&msg.actionType==NULL_RELEASE){
			_F_DEFAULT(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LEFT"&&msg.actionType==NULL_RELEASE){
			_F_LEFT(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="RIGHT"&&msg.actionType==NULL_RELEASE){
			_F_RIGHT(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="UP"&&msg.actionType==NULL_RELEASE){
			_F_UP(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="DOWN"&&msg.actionType==NULL_RELEASE){
			_F_DOWN(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LIST"&&msg.actionType==NULL_RELEASE){
			_F_LIST(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="MAIN"&&msg.actionType==NULL_RELEASE){
			_F_MAIN(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="SRC"&&msg.actionType==NULL_RELEASE){
			_F_SRC(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="CMD"&&msg.actionType==NULL_RELEASE){
			_F_CMD(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="SYS_H"&&msg.actionType==NULL_RELEASE){
			_F_SYS_H(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="USER_H"&&msg.actionType==NULL_RELEASE){
			_F_USER_H(msg);
			comsumer(msg);;
		}
	}
