
#include "EQ_EventV1.h"
	 EQ_EventV1::EQ_EventV1(){
		char *actionList[]={
		"banlance",
		"DEFAULT",
		"VOLUME",
		"LEFT",
		"LEFT_L",
		"LEFT_M",
		"LEFT_H",
		"RIGHT",
		"RIGHT_L",
		"RIGHT_M",
		"RIGHT_H",
		"LIST",
		"MAIN",
		"SRC",
		"CMD",
		"SYS_H",
		"USER_H",
		NULL};
		setActions(actionList);
		initScreen();	
	};
	void EQ_EventV1:: dispatch(MSG_ZHW&msg){
		if(msg.actionName=="banlance"&&msg.actionType==NULL_RELEASE){
			_F_banlance(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="DEFAULT"&&msg.actionType==NULL_RELEASE){
			_F_DEFAULT(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="VOLUME"&&msg.actionType==NULL_RELEASE){
			_F_VOLUME(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LEFT"&&msg.actionType==NULL_RELEASE){
			_F_LEFT(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LEFT_L"&&msg.actionType==NULL_RELEASE){
			_F_LEFT_L(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LEFT_M"&&msg.actionType==NULL_RELEASE){
			_F_LEFT_M(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LEFT_H"&&msg.actionType==NULL_RELEASE){
			_F_LEFT_H(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="RIGHT"&&msg.actionType==NULL_RELEASE){
			_F_RIGHT(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="RIGHT_L"&&msg.actionType==NULL_RELEASE){
			_F_RIGHT_L(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="RIGHT_M"&&msg.actionType==NULL_RELEASE){
			_F_RIGHT_M(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="RIGHT_H"&&msg.actionType==NULL_RELEASE){
			_F_RIGHT_H(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LIST"&&msg.actionType==NULL_RELEASE){
			_F_LIST(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="MAIN"&&msg.actionType==NULL_RELEASE){
			_F_MAIN(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="SRC"&&msg.actionType==NULL_RELEASE){
			_F_SRC(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="CMD"&&msg.actionType==NULL_RELEASE){
			_F_CMD(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="SYS_H"&&msg.actionType==NULL_RELEASE){
			_F_SYS_H(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="USER_H"&&msg.actionType==NULL_RELEASE){
			_F_USER_H(msg);
			comsumer(msg);;
		}
	}
