
#include "VOLUME_EventV1.h"
	 VOLUME_EventV1::VOLUME_EventV1(){
		char *actionList[]={
		"banlance",
		"eq",
		"DEFAULT",
		"LIST",
		"MAIN",
		"SRC",
		"CMD",
		"SYS_H",
		"USER_H",
		"LEFT_L",
		"LEFT_M",
		"LEFT_H",
		"RIGHT_L",
		"RIGHT_M",
		"RIGHT_H",
		"ONOFF",
		NULL};
		setActions(actionList);
		initScreen();	
	};
	void VOLUME_EventV1:: dispatch(MSG_ZHW&msg){
		if(msg.actionName=="banlance"&&msg.actionType==NULL_RELEASE){
			_F_banlance(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="eq"&&msg.actionType==NULL_RELEASE){
			_F_eq(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="DEFAULT"&&msg.actionType==NULL_RELEASE){
			_F_DEFAULT(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LIST"&&msg.actionType==NULL_RELEASE){
			_F_LIST(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="MAIN"&&msg.actionType==NULL_RELEASE){
			_F_MAIN(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="SRC"&&msg.actionType==NULL_RELEASE){
			_F_SRC(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="CMD"&&msg.actionType==NULL_RELEASE){
			_F_CMD(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="SYS_H"&&msg.actionType==NULL_RELEASE){
			_F_SYS_H(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="USER_H"&&msg.actionType==NULL_RELEASE){
			_F_USER_H(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LEFT_L"&&msg.actionType==NULL_RELEASE){
			_F_LEFT_L(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LEFT_M"&&msg.actionType==NULL_RELEASE){
			_F_LEFT_M(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LEFT_H"&&msg.actionType==NULL_RELEASE){
			_F_LEFT_H(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="RIGHT_L"&&msg.actionType==NULL_RELEASE){
			_F_RIGHT_L(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="RIGHT_M"&&msg.actionType==NULL_RELEASE){
			_F_RIGHT_M(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="RIGHT_H"&&msg.actionType==NULL_RELEASE){
			_F_RIGHT_H(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="ONOFF"&&msg.actionType==NULL_RELEASE){
			_F_ONOFF(msg);
			comsumer(msg);;
		}
	}
