
#include "RADIOLIST_EventV1.h"
	 RADIOLIST_EventV1::RADIOLIST_EventV1(){
		char *actionList[]={
		"FM",
		"LIST",
		"AM",
		"up",
		"down",
		"UPDATE",
		"RADIO",
		"EQ",
		NULL};
		setActions(actionList);
		initScreen();	
	};
	void RADIOLIST_EventV1:: dispatch(MSG_ZHW&msg){
		if(msg.actionName=="FM"&&msg.actionType==NULL_RELEASE){
			_F_FM(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="LIST"&&msg.actionType==NULL_RELEASE){
			_F_LIST(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="AM"&&msg.actionType==NULL_RELEASE){
			_F_AM(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="up"&&msg.actionType==NULL_RELEASE){
			_F_up(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="down"&&msg.actionType==NULL_RELEASE){
			_F_down(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="UPDATE"&&msg.actionType==NULL_RELEASE){
			_F_UPDATE(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="RADIO"&&msg.actionType==NULL_RELEASE){
			_F_RADIO(msg);
			comsumer(msg);;
		}
		if(msg.actionName=="EQ"&&msg.actionType==NULL_RELEASE){
			_F_EQ(msg);
			comsumer(msg);;
		}
	}
